version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.2.15
      KAFKA_CREATE_TOPICS: "FirstTopic:1:1, SecondTopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  consumer:
    build: Consumer/.
    image: consumer:1
  producer:
    build: Producer/.
    image: producer:1
